Mayank Raj
22BAI1118

# PERCEPTRON

In [206]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import joblib
from matplotlib.colors import ListedColormap


### Inference 
This cell sets up the necessary libraries for data manipulation, numerical computations, visualization, and model serialization. These libraries are essential for handling data, building models, and visualizing results.

In [207]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None, val: int=None):
        # Initialize the Perceptron with learning rate (eta), number of epochs, and number of inputs (val)
        self.val = val
        # Initialize weights with small random values
        self.weights = np.random.randn(val) * 1e-4  
        training = (eta is not None) and (epochs is not None)
        if training:
            print(f"Initial weights before training: \n{self.weights}\n")
        self.eta = eta  # Learning rate
        self.epochs = epochs  # Number of training epochs
    
    def _z_outcome(self, inputs, weights):
        # Calculate the linear combination of inputs and weights
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        # Apply the step function to the linear combination to get the binary output
        return np.where(z > 0, 1, 0)
    
    def fit(self, X, y):
        # Train the Perceptron model
        self.X = X
        self.y = y
        
        # Add bias term to the input data
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"Epoch {epoch}")
            print("--"*10)
            
            # Compute the linear combination
            z = self._z_outcome(X_with_bias, self.weights)
            # Get the predicted output
            y_hat = self.activation_function(z)
            
            # Compute the error
            self.error = self.y - y_hat
            
            # Update weights using the Perceptron learning rule
            self.weights += self.eta * np.dot(X_with_bias.T, self.error)
            print(f"Updated weights after epoch {epoch + 1}/{self.epochs}: \n{self.weights}")
    
    def predict(self, X):
        # Predict the output for given input data
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]  # Add bias term
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
    
    def total_loss(self):
        # Calculate and print the total loss (sum of errors)
        total_loss = np.sum(self.error)
        print(f"\nTotal loss: {total_loss}\n")
        return total_loss

### Inference
This cell defines the Perceptron class, including methods for initialization, training, prediction, and model management. The fit method trains the model by updating weights based on the errors computed from predictions. The predict method generates outputs for new data, and the save and load methods handle model persistence.

In [208]:
def prepare_data(df, target_col="y"):
    # Drop the target column to get the features (X)
    X = df.drop(target_col, axis=1)
    
    # Extract the target column (y)
    y = df[target_col]
    
    return X, y

### Inference
This function splits a DataFrame into features (X) and target labels (y) based on the specified target column. It prepares the data for training or evaluation by separating input features from the output labels.

# -> 2 Inputs

## AND

In [209]:
# Define the dataset for the AND gate
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,0,0,1]
}

# Create a DataFrame from the AND gate dataset
df_AND = pd.DataFrame(AND)

# Display the DataFrame
print(df_AND,"\n")

# Prepare the data by splitting into features (X) and target (y)
X, y = prepare_data(df_AND)

# Define the learning rate (ETA) and number of epochs
ETA = 0.1
EPOCHS = 10

# Initialize and train the Perceptron model
model_and = Perceptron(eta=ETA, epochs=EPOCHS, val=3)
model_and.fit(X, y)

# Calculate and print the total loss
_ = model_and.total_loss()


   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1 

Initial weights before training: 
[ 1.49786463e-04 -1.97290300e-04  3.47732404e-05]

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
Epoch 0
--------------------
Updated weights after epoch 1/10: 
[1.49786463e-04 9.98027097e-02 3.47732404e-05]
--------------------
Epoch 1
--------------------
Updated weights after epoch 2/10: 
[-9.98502135e-02 -1.97290300e-04  2.00034773e-01]
--------------------
Epoch 2
--------------------
Updated weights after epoch 3/10: 
[0.00014979 0.09980271 0.10003477]
--------------------
Epoch 3
--------------------
Updated weights after epoch 4/10: 
[1.00149786e-01 1.99802710e-01 3.47732404e-05]
--------------------
Epoch 4
--------------------
Updated weights after epoch 5/10: 
[1.49786463e-04 9.98027097e-02 2.00034773e-01]
--------------------
Epoch 5
--------------------
Updated weights after epoch 6/10: 
[0.10014979 0.19980271 0.10003477]
--

### Inference
This cell sets up and trains a Perceptron model using a dataset for the AND gate. It initializes the model with a learning rate and number of epochs, trains it on the provided data, and calculates the total loss to evaluate model performance. The DataFrame df_AND contains the input-output pairs for the AND gate.

## OR

In [210]:
# Define the dataset for the OR gate
OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,1]
}

# Create a DataFrame from the OR gate dataset
df_OR = pd.DataFrame(OR)

# Display the DataFrame
print(df_OR,"\n")

# Prepare the data by splitting into features (X) and target (y)
X, y = prepare_data(df_OR)

# Define the learning rate (ETA) and number of epochs
ETA = 0.1
EPOCHS = 10

# Initialize and train the Perceptron model
model_or = Perceptron(eta=ETA, epochs=EPOCHS, val=3)
model_or.fit(X, y)

# Calculate and print the total loss
_ = model_or.total_loss()


   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1 

Initial weights before training: 
[-9.66757042e-05  9.76194352e-05 -1.46319294e-05]

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
Epoch 0
--------------------
Updated weights after epoch 1/10: 
[ 9.99033243e-02  9.76194352e-05 -1.46319294e-05]
--------------------
Epoch 1
--------------------
Updated weights after epoch 2/10: 
[9.99033243e-02 9.76194352e-05 9.99853681e-02]
--------------------
Epoch 2
--------------------
Updated weights after epoch 3/10: 
[ 0.19990332  0.10009762 -0.10001463]
--------------------
Epoch 3
--------------------
Updated weights after epoch 4/10: 
[ 1.99903324e-01  1.00097619e-01 -1.46319294e-05]
--------------------
Epoch 4
--------------------
Updated weights after epoch 5/10: 
[0.19990332 0.10009762 0.09998537]
--------------------
Epoch 5
--------------------
Updated weights after epoch 6/10: 
[0.19990332 0.10009762 0.09998537]
--------

### Inference
This cell sets up and trains a Perceptron model using a dataset for the OR gate. It initializes the model with specified learning rate and number of epochs, trains it on the OR gate data, and calculates the total loss to assess the model’s performance. The DataFrame df_OR contains input-output pairs for the OR gate.

## XOR

In [211]:
# Define the dataset for the XOR gate
XOR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,0]
}

# Create a DataFrame from the XOR gate dataset
df_XOR = pd.DataFrame(XOR)

# Display the DataFrame
print(df_XOR,"\n")

# Prepare the data by splitting into features (X) and target (y)
X, y = prepare_data(df_XOR)

# Define the learning rate (ETA) and number of epochs
ETA = 0.1
EPOCHS = 10

# Initialize and train the Perceptron model
model_xor = Perceptron(eta=ETA, epochs=EPOCHS, val=3)
model_xor.fit(X, y)

# Calculate and print the total loss
_ = model_xor.total_loss()


   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0 

Initial weights before training: 
[-5.32025732e-06 -9.54486435e-05 -6.31422706e-05]

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
Epoch 0
--------------------
Updated weights after epoch 1/10: 
[-5.32025732e-06  9.99045514e-02 -6.31422706e-05]
--------------------
Epoch 1
--------------------
Updated weights after epoch 2/10: 
[-1.00005320e-01 -9.54486435e-05  1.99936858e-01]
--------------------
Epoch 2
--------------------
Updated weights after epoch 3/10: 
[-5.32025732e-06  9.99045514e-02 -6.31422706e-05]
--------------------
Epoch 3
--------------------
Updated weights after epoch 4/10: 
[-1.00005320e-01 -9.54486435e-05  1.99936858e-01]
--------------------
Epoch 4
--------------------
Updated weights after epoch 5/10: 
[-5.32025732e-06  9.99045514e-02 -6.31422706e-05]
--------------------
Epoch 5
--------------------
Updated weights after epoch 6/10: 
[-1.00005320e

### Inference
This cell sets up and trains a Perceptron model using a dataset for the XOR gate. The DataFrame df_XOR holds the XOR gate input-output pairs. The model is trained with the specified learning rate and epochs, and the total loss is computed to evaluate how well the model has learned the XOR function.

In [212]:
# Model prediction function for logical operations
def model_predict(input_data, operation='AND'):
    if operation == 'AND':
        return np.all(input_data == 1, axis=1).astype(int)
    elif operation == 'OR':
        return np.any(input_data == 1, axis=1).astype(int)
    elif operation == 'XOR':
        return np.logical_xor.reduce(input_data, axis=1).astype(int)
    else:
        raise ValueError("Unsupported operation. Choose from 'AND', 'OR', 'XOR'.")

# Accuracy function
def calculate_accuracy(predictions, targets):
    correct_predictions = np.sum(predictions == targets)
    total_predictions = len(targets)
    accuracy = correct_predictions / total_predictions
    return accuracy

# Test cases for logical gates
test_cases = np.array([
    [[0, 0]], 
    [[0, 1]], 
    [[1, 0]], 
    [[1, 1]]
])

# Expected outputs for AND, OR, and XOR gates
expected_outputs_and = np.array([0, 0, 0, 1])
expected_outputs_or = np.array([0, 1, 1, 1])
expected_outputs_xor = np.array([0, 1, 1, 0])

# Function to evaluate predictions and print accuracy
def evaluate_model(test_cases, expected_outputs, operation):
    predictions = np.array([model_predict(case, operation) for case in test_cases])
    print(f"\nEvaluating {operation} gate:")
    for case, prediction, expected in zip(test_cases, predictions, expected_outputs):
        print(f"Input: {case.flatten()}, Output: {prediction[0]}, Expected: {expected}")
    accuracy = calculate_accuracy(predictions.flatten(), expected_outputs)
    print(f"Overall Accuracy for {operation}: {accuracy * 100:.2f}%\n")

# Evaluate for different operations
evaluate_model(test_cases, expected_outputs_and, 'AND')
evaluate_model(test_cases, expected_outputs_or, 'OR')
evaluate_model(test_cases, expected_outputs_xor, 'XOR')



Evaluating AND gate:
Input: [0 0], Output: 0, Expected: 0
Input: [0 1], Output: 0, Expected: 0
Input: [1 0], Output: 0, Expected: 0
Input: [1 1], Output: 1, Expected: 1
Overall Accuracy for AND: 100.00%


Evaluating OR gate:
Input: [0 0], Output: 0, Expected: 0
Input: [0 1], Output: 1, Expected: 1
Input: [1 0], Output: 1, Expected: 1
Input: [1 1], Output: 1, Expected: 1
Overall Accuracy for OR: 100.00%


Evaluating XOR gate:
Input: [0 0], Output: 0, Expected: 0
Input: [0 1], Output: 1, Expected: 1
Input: [1 0], Output: 1, Expected: 1
Input: [1 1], Output: 0, Expected: 0
Overall Accuracy for XOR: 100.00%



### Inference
This cell defines a function to predict the output for logical operations (AND, OR, XOR) and calculates the accuracy of these predictions. It tests each logical operation using predefined test cases, compares the predictions against expected outputs, and prints the results and accuracy for each operation.

# -> 3 Inputs

## AND

In [213]:
# Prepare data for AND operation with an additional input
AND = {
    "x1": [0, 0, 1, 1],
    "x2": [0, 1, 0, 1],
    "x3": [0, 0, 0, 1],  
    "y" : [0, 0, 0, 1]
}

# Create a DataFrame from the AND gate dataset
df_AND = pd.DataFrame(AND)
print(df_AND,"\n")
# Split the DataFrame into features (X) and target (y)
X, y = df_AND.drop('y', axis=1).values, df_AND['y'].values

# Define the learning rate (ETA) and number of epochs
ETA = 0.1
EPOCHS = 10

# Initialize and train the Perceptron model with 3 inputs (plus bias)
model_and = Perceptron(eta=ETA, epochs=EPOCHS, val=4)
model_and.fit(X, y)

# Calculate and print the total loss
_ = model_and.total_loss()


   x1  x2  x3  y
0   0   0   0  0
1   0   1   0  0
2   1   0   0  0
3   1   1   1  1 

Initial weights before training: 
[ 4.03079223e-05  5.11276523e-05  4.10597727e-05 -2.41330015e-04]

X with bias: 
[[ 0.  0.  0. -1.]
 [ 0.  1.  0. -1.]
 [ 1.  0.  0. -1.]
 [ 1.  1.  1. -1.]]
--------------------
Epoch 0
--------------------
Updated weights after epoch 1/10: 
[-9.99596921e-02 -9.99488723e-02  4.10597727e-05  2.99758670e-01]
--------------------
Epoch 1
--------------------
Updated weights after epoch 2/10: 
[4.03079223e-05 5.11276523e-05 1.00041060e-01 1.99758670e-01]
--------------------
Epoch 2
--------------------
Updated weights after epoch 3/10: 
[0.10004031 0.10005113 0.20004106 0.09975867]
--------------------
Epoch 3
--------------------
Updated weights after epoch 4/10: 
[4.03079223e-05 5.11276523e-05 2.00041060e-01 2.99758670e-01]
--------------------
Epoch 4
--------------------
Updated weights after epoch 5/10: 
[0.10004031 0.10005113 0.30004106 0.19975867]
--------------

### Inference
This cell prepares and trains a Perceptron model for a 3-input AND gate. The dataset AND now includes three input features. The Perceptron is trained with the specified learning rate and number of epochs. The total loss is computed to assess the model’s performance.

## OR

In [214]:
# Prepare data for OR operation with an additional input
OR = {
    "x1": [0, 0, 1, 1],
    "x2": [0, 1, 0, 1],
    "x3": [0, 0, 1, 1],  
    "y" : [0, 1, 1, 1]
}

# Create a DataFrame from the OR gate dataset
df_OR = pd.DataFrame(OR)
print(df_OR, "\n")  # Print the DataFrame to check the data

# Split the DataFrame into features (X) and target (y)
X, y = df_OR.drop('y', axis=1).values, df_OR['y'].values

# Define the learning rate (ETA) and number of epochs
ETA = 0.1
EPOCHS = 10

# Initialize and train the Perceptron model with 3 inputs (plus bias)
model_or = Perceptron(eta=ETA, epochs=EPOCHS, val=4)
model_or.fit(X, y)

# Calculate and print the total loss
_ = model_or.total_loss()


   x1  x2  x3  y
0   0   0   0  0
1   0   1   0  1
2   1   0   1  1
3   1   1   1  1 

Initial weights before training: 
[-8.85092058e-05  3.41192450e-05  1.28401700e-04  1.83756785e-04]

X with bias: 
[[ 0.  0.  0. -1.]
 [ 0.  1.  0. -1.]
 [ 1.  0.  1. -1.]
 [ 1.  1.  1. -1.]]
--------------------
Epoch 0
--------------------
Updated weights after epoch 1/10: 
[ 0.19991149  0.20003412  0.2001284  -0.29981624]
--------------------
Epoch 1
--------------------
Updated weights after epoch 2/10: 
[ 0.19991149  0.20003412  0.2001284  -0.19981624]
--------------------
Epoch 2
--------------------
Updated weights after epoch 3/10: 
[ 0.19991149  0.20003412  0.2001284  -0.09981624]
--------------------
Epoch 3
--------------------
Updated weights after epoch 4/10: 
[1.99911491e-01 2.00034119e-01 2.00128402e-01 1.83756785e-04]
--------------------
Epoch 4
--------------------
Updated weights after epoch 5/10: 
[1.99911491e-01 2.00034119e-01 2.00128402e-01 1.83756785e-04]
--------------------
E

### Inference
This cell prepares and trains a Perceptron model for a 3-input OR gate. The dataset OR now includes three input features. The model is trained with the specified learning rate and number of epochs, and the total loss is calculated to evaluate the model’s performance.

## XOR

In [215]:
# Prepare data for XOR operation with an additional input
XOR = {
    "x1": [0, 0, 1, 1],
    "x2": [0, 1, 0, 1],
    "x3": [0, 1, 1, 0],  
    "y" : [0, 1, 1, 0]
}

# Create a DataFrame from the XOR gate dataset
df_XOR = pd.DataFrame(XOR)
print(df_XOR, "\n")  # Print the DataFrame to check the data

# Split the DataFrame into features (X) and target (y)
X, y = df_XOR.drop('y', axis=1).values, df_XOR['y'].values

# Define the learning rate (ETA) and number of epochs
ETA = 0.1
EPOCHS = 10
# Initialize and train the Perceptron model with 3 inputs (plus bias)
model_xor = Perceptron(eta=ETA, epochs=EPOCHS, val=4)
model_xor.fit(X, y)

# Calculate and print the total loss
_ = model_xor.total_loss()


   x1  x2  x3  y
0   0   0   0  0
1   0   1   1  1
2   1   0   1  1
3   1   1   0  0 

Initial weights before training: 
[-7.15494057e-05  1.62221391e-04  1.00105604e-05 -1.36912591e-04]

X with bias: 
[[ 0.  0.  0. -1.]
 [ 0.  1.  1. -1.]
 [ 1.  0.  1. -1.]
 [ 1.  1.  0. -1.]]
--------------------
Epoch 0
--------------------
Updated weights after epoch 1/10: 
[-1.00071549e-01 -9.98377786e-02  1.00105604e-05  1.99863087e-01]
--------------------
Epoch 1
--------------------
Updated weights after epoch 2/10: 
[-7.15494057e-05  1.62221391e-04  2.00010011e-01 -1.36912591e-04]
--------------------
Epoch 2
--------------------
Updated weights after epoch 3/10: 
[-0.10007155 -0.09983778  0.20001001  0.19986309]
--------------------
Epoch 3
--------------------
Updated weights after epoch 4/10: 
[-7.15494057e-05  1.62221391e-04  4.00010011e-01 -1.36912591e-04]
--------------------
Epoch 4
--------------------
Updated weights after epoch 5/10: 
[-0.10007155 -0.09983778  0.40001001  0.19986309

### Inference
This cell prepares and trains a Perceptron model for a 3-input XOR gate. The dataset XOR now includes three input features. The model is trained with the specified learning rate and number of epochs, and the total loss is computed to assess the model’s performance.

In [216]:
# Define prediction and accuracy functions
def model_predict(input_data, operation='AND'):
    if operation == 'AND':
        return np.all(input_data == 1, axis=1).astype(int)
    elif operation == 'OR':
        return np.any(input_data == 1, axis=1).astype(int)
    elif operation == 'XOR':
        return np.logical_xor.reduce(input_data, axis=1).astype(int)
    else:
        raise ValueError("Unsupported operation. Choose from 'AND', 'OR', 'XOR'.")

def calculate_accuracy(predictions, targets):
    correct_predictions = np.sum(predictions == targets)
    total_predictions = len(targets)
    accuracy = correct_predictions / total_predictions
    return accuracy

# Function to evaluate predictions and print accuracy
def evaluate_model(X, y, model, operation):
    predictions = model.predict(X).flatten()  # Predict using the model
    print(f"\nEvaluating {operation} gate:")
    for case, prediction, expected in zip(X, predictions, y):
        print(f"Input: {case}, Output: {prediction}, Expected: {expected}")
    accuracy = calculate_accuracy(predictions, y)  # Calculate accuracy
    print(f"Overall Accuracy for {operation}: {accuracy * 100:.2f}%\n")

# Evaluate each logical operation using the trained models
evaluate_model(df_AND.drop('y', axis=1).values, df_AND['y'].values, model_and, 'AND')
evaluate_model(df_OR.drop('y', axis=1).values, df_OR['y'].values, model_or, 'OR')
evaluate_model(df_XOR.drop('y', axis=1).values, df_XOR['y'].values, model_xor, 'XOR')



Evaluating AND gate:
Input: [0 0 0], Output: 0, Expected: 0
Input: [0 1 0], Output: 0, Expected: 0
Input: [1 0 0], Output: 0, Expected: 0
Input: [1 1 1], Output: 1, Expected: 1
Overall Accuracy for AND: 100.00%


Evaluating OR gate:
Input: [0 0 0], Output: 0, Expected: 0
Input: [0 1 0], Output: 1, Expected: 1
Input: [1 0 1], Output: 1, Expected: 1
Input: [1 1 1], Output: 1, Expected: 1
Overall Accuracy for OR: 100.00%


Evaluating XOR gate:
Input: [0 0 0], Output: 0, Expected: 0
Input: [0 1 1], Output: 1, Expected: 1
Input: [1 0 1], Output: 1, Expected: 1
Input: [1 1 0], Output: 0, Expected: 0
Overall Accuracy for XOR: 100.00%



### Inference
This cell defines functions to predict results based on logical operations (AND, OR, XOR) and to calculate accuracy. It then evaluates the trained Perceptron models for each logical operation by comparing predictions with expected results and calculates the overall accuracy for each gate.

# -> 4 Inputs


## AND

In [217]:
# Define data for AND operation with 4 inputs
AND = {
    "x1": [0, 0, 1, 1],
    "x2": [0, 1, 0, 1],
    "x3": [0, 0, 0, 1],
    "x4": [0, 0, 0, 1],  
    "y" : [0, 0, 0, 1]
}

# Create DataFrame from the dictionary
df_AND = pd.DataFrame(AND)
print(df_AND, "\n")  # Print the DataFrame to check the data

# Separate features and target variable
X, y = df_AND.drop('y', axis=1).values, df_AND['y'].values

# Define training parameters
ETA = 0.1
EPOCHS = 10

# Create and train the Perceptron model
model_and = Perceptron(eta=ETA, epochs=EPOCHS, val=5)  # 5 input features
model_and.fit(X, y)  # Train the model
_ = model_and.total_loss()  # Compute and print total loss


   x1  x2  x3  x4  y
0   0   0   0   0  0
1   0   1   0   0  0
2   1   0   0   0  0
3   1   1   1   1  1 

Initial weights before training: 
[ 4.02393777e-07  5.56660983e-05 -2.57429963e-04  2.00968369e-04
  3.20488988e-05]

X with bias: 
[[ 0.  0.  0.  0. -1.]
 [ 0.  1.  0.  0. -1.]
 [ 1.  0.  0.  0. -1.]
 [ 1.  1.  1.  1. -1.]]
--------------------
Epoch 0
--------------------
Updated weights after epoch 1/10: 
[1.00000402e-01 5.56660983e-05 9.97425700e-02 1.00200968e-01
 3.20488988e-05]
--------------------
Epoch 1
--------------------
Updated weights after epoch 2/10: 
[ 4.02393777e-07 -9.99443339e-02  9.97425700e-02  1.00200968e-01
  2.00032049e-01]
--------------------
Epoch 2
--------------------
Updated weights after epoch 3/10: 
[1.00000402e-01 5.56660983e-05 1.99742570e-01 2.00200968e-01
 1.00032049e-01]
--------------------
Epoch 3
--------------------
Updated weights after epoch 4/10: 
[1.00000402e-01 5.56660983e-05 1.99742570e-01 2.00200968e-01
 1.00032049e-01]
-----------

### Inference
This cell sets up and trains a Perceptron model for an AND operation with four input features. The data includes an additional input feature (x4) to match the increased dimensionality. The model is trained over 1000 epochs with a learning rate of 0.1, and the total loss is computed to assess the training process.

## OR

In [218]:
# Define data for OR operation with 4 inputs
OR = {
    "x1": [0, 0, 1, 1],
    "x2": [0, 1, 0, 1],
    "x3": [0, 0, 1, 1],  
    "x4": [0, 1, 1, 1],  
    "y" : [0, 1, 1, 1]
}

# Create DataFrame from the dictionary
df_OR = pd.DataFrame(OR)
print(df_OR, "\n")  # Print the DataFrame to check the data

# Separate features and target variable
X, y = df_OR.drop('y', axis=1).values, df_OR['y'].values

# Define training parameters
ETA = 0.1
EPOCHS = 10

# Create and train the Perceptron model
model_or = Perceptron(eta=ETA, epochs=EPOCHS, val=5)  # 5 input features
model_or.fit(X, y)  # Train the model
_ = model_or.total_loss()  # Compute and print total loss


   x1  x2  x3  x4  y
0   0   0   0   0  0
1   0   1   0   1  1
2   1   0   1   1  1
3   1   1   1   1  1 

Initial weights before training: 
[ 9.68937027e-05  4.06499357e-05  1.45932454e-04 -1.48323301e-05
 -1.54967005e-04]

X with bias: 
[[ 0.  0.  0.  0. -1.]
 [ 0.  1.  0.  1. -1.]
 [ 1.  0.  1.  1. -1.]
 [ 1.  1.  1.  1. -1.]]
--------------------
Epoch 0
--------------------
Updated weights after epoch 1/10: 
[ 9.68937027e-05  4.06499357e-05  1.45932454e-04 -1.48323301e-05
  9.98450330e-02]
--------------------
Epoch 1
--------------------
Updated weights after epoch 2/10: 
[ 0.20009689  0.20004065  0.20014593  0.29998517 -0.20015497]
--------------------
Epoch 2
--------------------
Updated weights after epoch 3/10: 
[ 0.20009689  0.20004065  0.20014593  0.29998517 -0.10015497]
--------------------
Epoch 3
--------------------
Updated weights after epoch 4/10: 
[ 2.00096894e-01  2.00040650e-01  2.00145932e-01  2.99985168e-01
 -1.54967005e-04]
--------------------
Epoch 4
---------

### Inference
This cell prepares and trains a Perceptron model for an OR operation with four input features. It includes data with an additional input feature (x4). The model is trained with the same parameters (1000 epochs and a learning rate of 0.1), and the total loss is calculated to evaluate training performance.

## XOR

In [219]:
# Define data for XOR operation with 4 inputs
XOR = {
    "x1": [0, 0, 1, 1],
    "x2": [0, 1, 0, 1],
    "x3": [0, 1, 1, 0],  
    "x4": [0, 1, 0, 1], 
    "y" : [0, 1, 1, 0]
}

# Create DataFrame from the dictionary
df_XOR = pd.DataFrame(XOR)
print(df_XOR, "\n")  # Print the DataFrame to check the data

# Separate features and target variable
X, y = df_XOR.drop('y', axis=1).values, df_XOR['y'].values

# Define training parameters
ETA = 0.1
EPOCHS = 10

# Create and train the Perceptron model
model_xor = Perceptron(eta=ETA, epochs=EPOCHS, val=5)  # 5 input features
model_xor.fit(X, y)  # Train the model
_ = model_xor.total_loss()  # Compute and print total loss


   x1  x2  x3  x4  y
0   0   0   0   0  0
1   0   1   1   1  1
2   1   0   1   0  1
3   1   1   0   1  0 

Initial weights before training: 
[ 1.41893020e-04  1.10135969e-04 -1.53577436e-04 -8.47705474e-05
  1.30557912e-04]

X with bias: 
[[ 0.  0.  0.  0. -1.]
 [ 0.  1.  1.  1. -1.]
 [ 1.  0.  1.  0. -1.]
 [ 1.  1.  0.  1. -1.]]
--------------------
Epoch 0
--------------------
Updated weights after epoch 1/10: 
[ 1.41893020e-04  1.10135969e-04  1.99846423e-01 -8.47705474e-05
 -9.98694421e-02]
--------------------
Epoch 1
--------------------
Updated weights after epoch 2/10: 
[-0.09985811 -0.09988986  0.19984642 -0.10008477  0.10013056]
--------------------
Epoch 2
--------------------
Updated weights after epoch 3/10: 
[ 1.41893020e-04  1.10135969e-04  3.99846423e-01 -8.47705474e-05
 -9.98694421e-02]
--------------------
Epoch 3
--------------------
Updated weights after epoch 4/10: 
[-0.09985811 -0.09988986  0.39984642 -0.10008477  0.10013056]
--------------------
Epoch 4
---------

### Inference
This cell prepares and trains a Perceptron model for an XOR operation with four input features. The data includes an additional input feature (x4). The model is trained with the same parameters (1000 epochs and a learning rate of 0.1), and the total loss is calculated to assess training performance.

In [220]:
# Define prediction function based on the logical operation
def model_predict(input_data, operation='AND'):
    if operation == 'AND':
        return np.all(input_data == 1, axis=1).astype(int)  # AND operation
    elif operation == 'OR':
        return np.any(input_data == 1, axis=1).astype(int)  # OR operation
    elif operation == 'XOR':
        return np.logical_xor.reduce(input_data, axis=1).astype(int)  # XOR operation
    else:
        raise ValueError("Unsupported operation. Choose from 'AND', 'OR', 'XOR'.")

# Calculate accuracy of predictions
def calculate_accuracy(predictions, targets):
    correct_predictions = np.sum(predictions == targets)  # Count correct predictions
    total_predictions = len(targets)  # Total number of predictions
    accuracy = correct_predictions / total_predictions  # Calculate accuracy
    return accuracy

# Evaluate and print predictions and accuracy for the model
def evaluate_model(X, y, model, operation):
    predictions = model.predict(X).flatten()  # Get model predictions
    print(f"\nEvaluating {operation} gate:")
    for case, prediction, expected in zip(X, predictions, y):
        print(f"Input: {case}, Output: {prediction}, Expected: {expected}")  # Print each case
    accuracy = calculate_accuracy(predictions, y)  # Calculate accuracy
    print(f"Overall Accuracy for {operation}: {accuracy * 100:.2f}%\n")  # Print accuracy

# Evaluate models for different logical operations
evaluate_model(df_AND.drop('y', axis=1).values, df_AND['y'].values, model_and, 'AND')
evaluate_model(df_OR.drop('y', axis=1).values, df_OR['y'].values, model_or, 'OR')
evaluate_model(df_XOR.drop('y', axis=1).values, df_XOR['y'].values, model_xor, 'XOR')



Evaluating AND gate:
Input: [0 0 0 0], Output: 0, Expected: 0
Input: [0 1 0 0], Output: 0, Expected: 0
Input: [1 0 0 0], Output: 0, Expected: 0
Input: [1 1 1 1], Output: 1, Expected: 1
Overall Accuracy for AND: 100.00%


Evaluating OR gate:
Input: [0 0 0 0], Output: 0, Expected: 0
Input: [0 1 0 1], Output: 1, Expected: 1
Input: [1 0 1 1], Output: 1, Expected: 1
Input: [1 1 1 1], Output: 1, Expected: 1
Overall Accuracy for OR: 100.00%


Evaluating XOR gate:
Input: [0 0 0 0], Output: 0, Expected: 0
Input: [0 1 1 1], Output: 1, Expected: 1
Input: [1 0 1 0], Output: 1, Expected: 1
Input: [1 1 0 1], Output: 0, Expected: 0
Overall Accuracy for XOR: 100.00%



### Inference
This cell defines functions for predicting and calculating accuracy based on logical operations (AND, OR, XOR). It also evaluates the Perceptron models for each operation (with 4 inputs) by comparing predictions against expected outcomes and calculating the accuracy of each model.